name: Auto assign/unassign issues

permissions:
  contents: read
  issues: write

on:
  issue_comment:
    types: [created]

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: jpmcb/prow-github-actions@v2.0.0
        with:
          prow-commands: /assign /unassign 
          github-token: '${{ secrets.GITHUB_TOKEN }}'
